language: csharp
mono: alpha
sudo: required
dist: trusty
dotnet:
  - 1.0.1
  - 2.0.0
addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
env:
  - MONO_TLS_PROVIDER=legacy
install:
  - dotnet restore
script: ./build.sh --target=test && ./build.sh --target=pack